/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interafaces;

/**
 *
 * @author MICHEL NINA ZARATE
 */
// Swing
import javax.swing.*;

// Eventos
import java.awt.event.*;

// JDBC
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

// JavaMail
import java.util.Properties;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
// Utilidades
import java.util.Random;
import java.util.logging.*;

public class VentanaOlvidasteContraseña extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaOlvidasteContraseña.class.getName());
    private String codigoGenerado; 
    /**
     * Creates new form VentanaOlvidasteContraseña
     */
    public VentanaOlvidasteContraseña() {
        initComponents();
    }

    private void enviarCorreo(String destinatario, String codigo) {
        final String remitente = "monsteru412@gmail.com"; // tu Gmail
        final String clave = "zauh hpcr cjfc fjmj"; // contraseña de aplicación

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
        new jakarta.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(remitente, clave);
            }
        }
        );

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(remitente));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
            message.setSubject("Recuperación de Contraseña");
            message.setText("Tu código de verificación es: " + codigo);

            Transport.send(message);
            System.out.println("Correo enviado correctamente.");
        } catch (MessagingException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al enviar correo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGmail = new javax.swing.JTextField();
        btnEnviarGmail = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnValCod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGmailActionPerformed(evt);
            }
        });

        btnEnviarGmail.setText("Enviar a gmail");
        btnEnviarGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarGmailActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnValCod.setText("Validar Codigo");
        btnValCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValCod)
                    .addComponent(btnEnviarGmail))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtGmail))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarGmail)
                .addGap(74, 74, 74)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValCod)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGmailActionPerformed

    private void btnEnviarGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarGmailActionPerformed
        // TODO add your handling code here:                                              
    String correo = txtGmail.getText().trim();

    if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese su correo");
        return;
    }

    // Generar código aleatorio (6 dígitos)
    codigoGenerado = String.valueOf((int)(Math.random() * 900000) + 100000);

    try (Connection con = conexionbd.conexion.getConnection()) {
        // Guardar en la base de datos
        String sql = "INSERT INTO recuperacion_contrasena (correo, codigo, expiracion) VALUES (?, ?, DATE_ADD(NOW(), INTERVAL 15 MINUTE))";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, correo);
        ps.setString(2, codigoGenerado);
        ps.executeUpdate();

        // Enviar el código al correo
        enviarCorreo(correo, codigoGenerado);

        JOptionPane.showMessageDialog(this, "Se envió un código a tu correo");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }


    }//GEN-LAST:event_btnEnviarGmailActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnValCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValCodActionPerformed
        // TODO add your handling code here:
        String codigoIngresado = txtCodigo.getText().trim();

        if (codigoIngresado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código recibido");
            return;
        }

        if (codigoIngresado.equals(codigoGenerado)) {
            JOptionPane.showMessageDialog(this, "Código correcto, puede cambiar su contraseña");

    // Abrir la ventana para crear nueva contraseña
            CrearNuevaContraseña nuevaVentana = new CrearNuevaContraseña(txtGmail.getText().trim());
            nuevaVentana.setVisible(true);

    // Cerrar la ventana actual
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Código incorrecto");
        }

    }//GEN-LAST:event_btnValCodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaOlvidasteContraseña().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarGmail;
    private javax.swing.JButton btnValCod;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGmail;
    // End of variables declaration//GEN-END:variables
}
