/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interafaces;

import conexionbd.conexion;
import java.sql.*;
import javax.swing.*;

public class VentanaPostulante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPostulante.class.getName());
    
    private String usuario;
    private String nombre;
    private String apellidoP;
    private String apellidoM;

    public VentanaPostulante() {
        initComponents();
    }

    public VentanaPostulante(String usuario, String nombre, String apellidoP, String apellidoM) {
        initComponents();
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellidoP = apellidoP;
        this.apellidoM = apellidoM;

        // Ejemplo: mostrar un mensaje en la ventana
        setTitle("Bienvenido " + nombre + " " + apellidoP + " " + apellidoM);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQR.setText("Ir a generaQR");
        btnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnQR)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(btnQR)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQRActionPerformed
        // TODO add your handling code here:
        String nombre = this.nombre;
        String apellidoP = this.apellidoP;
        String apellidoM = this.apellidoM;
        String ci = this.usuario; // CI del postulante desde login
        double monto = 500.00; // ejemplo

        try (Connection con = conexion.getConnection()) {

    // Verificar si ya existe un pago para este CI
            String checkSql = "SELECT * FROM pago WHERE ci_postulante=? ORDER BY fecha_registro DESC LIMIT 1";
            PreparedStatement psCheck = con.prepareStatement(checkSql);
            psCheck.setString(1, ci);
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                String estado = rs.getString("estado");

                if (estado.equals("PENDIENTE")) {
            // Abrir ventana de QR sobre el pago pendiente existente
                    VentanaGenerarQR vqr = new VentanaGenerarQR(ci, nombre, apellidoP, apellidoM, monto);
                    vqr.setVisible(true);
                } else {
            // Si ya está PAGADO
                JOptionPane.showMessageDialog(this, "Usted ya ha pagado.");
                }

            } else {
        // No existe ningún pago, crear nuevo registro pendiente
                String insertSql = "INSERT INTO pago(ci_postulante, monto, estado) VALUES (?, ?, 'PENDIENTE')";
                PreparedStatement psInsert = con.prepareStatement(insertSql);
                psInsert.setString(1, ci);
                psInsert.setDouble(2, monto);
                psInsert.executeUpdate();

        // Abrir ventana de QR sobre el nuevo registro
                VentanaGenerarQR vqr = new VentanaGenerarQR(ci, nombre, apellidoP, apellidoM, monto);
                vqr.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPostulante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQR;
    // End of variables declaration//GEN-END:variables
}
